const BASE = '/opt/teen/services'
const ENV_FILE = (svc) => `${BASE}/${svc}/.env`

module.exports = {
  apps: [
    {
      name: 'teen-auth',
      cwd: `${BASE}/auth-service`,
      script: 'dist/index.js',
      env_file: ENV_FILE('auth-service'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'teen-user',
      cwd: `${BASE}/user-service`,
      script: 'dist/index.js',
      env_file: ENV_FILE('user-service'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'teen-wallet',
      cwd: `${BASE}/wallet-service`,
      script: 'dist/index.js',
      env_file: ENV_FILE('wallet-service'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'teen-gateway',
      cwd: `${BASE}/game-gateway`,
      script: 'dist/index.js',
      env_file: ENV_FILE('game-gateway'),
      // Cluster mode: enabled by adding Redis Pub/Sub cluster fan-out broker.
      instances: 'max',
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '400M',
    },
    {
      name: 'teen-aviator',
      cwd: `${BASE}/game-engines/aviator`,
      script: 'dist/index.js',
      env_file: ENV_FILE('game-engines/aviator'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'teen-ludo',
      cwd: `${BASE}/game-engines/ludo`,
      script: 'dist/index.js',
      env_file: ENV_FILE('game-engines/ludo'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'teen-betting',
      cwd: `${BASE}/betting-service`,
      script: 'dist/index.js',
      env_file: ENV_FILE('betting-service'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '300M',
    },
    {
      name: 'teen-leaderboard',
      cwd: `${BASE}/leaderboard-service`,
      script: 'dist/index.js',
      env_file: ENV_FILE('leaderboard-service'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'teen-notify',
      cwd: `${BASE}/notification-service`,
      script: 'dist/index.js',
      env_file: ENV_FILE('notification-service'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'teen-admin-svc',
      cwd: `${BASE}/admin-service`,
      script: 'dist/index.js',
      env_file: ENV_FILE('admin-service'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'teen-monitoring',
      cwd: `${BASE}/monitoring-service`,
      script: 'dist/index.js',
      env_file: ENV_FILE('monitoring-service'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '200M',
    },
    {
      name: 'teen-risk',
      cwd: `${BASE}/risk-service`,
      script: 'dist/index.js',
      env_file: ENV_FILE('risk-service'),
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '200M',
    },
  ],
}
